services:
  - type: web
    name: akash-share-backend
    runtime: node
    plan: free
    buildCommand: "cd backend && rm -rf node_modules package-lock.json && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
